id: mirror-2
name: mirror

synonyms: [reflection, enormous]
start: mirror-room-2

actions:
  - id: get
    triggers:
      - type: response
        data: { text: The mirror is many times your size. Give up. }

  - id: break
    requires:
      - type: flag
        negate: true
        data: { flag: mirror-mung }
        failure:
          triggers:
            - type: response
              data:
                text: "Haven't you done enough damage already?"
    triggers:
      - type: response
        data:
          text: >-
            You have broken the mirror. I hope you have a seven years' supply of good luck
            handy.
      - type: set-flag
        data: { flag: mirror-mung, value: true }

  - id: attack
    requires:
      - type: flag
        negate: true
        data: { flag: mirror-mung }
        failure:
          triggers:
            - type: response
              data:
                text: "Haven't you done enough damage already?"
    triggers:
      - type: response
        data:
          text: >-
            You have broken the mirror. I hope you have a seven years' supply of good luck
            handy.
      - type: set-flag
        data: { flag: mirror-mung, value: true }

  - id: throw
    requires:
      - type: flag
        negate: true
        data: { flag: mirror-mung }
        failure:
          triggers:
            - type: response
              data:
                text: "Haven't you done enough damage already?"
    triggers:
      - type: response
        data:
          text: >-
            You have broken the mirror. I hope you have a seven years' supply of good luck
            handy.
      - type: set-flag
        data: { flag: mirror-mung, value: true }

  - id: look
    requires:
      - type: flag
        data: { flag: mirror-mung }
    triggers:
      - type: response
        data: { text: The mirror is broken into many pieces. }

  - id: look
    triggers:
      - type: response
        data: { text: There is an ugly person staring back at you. }

  - id: touch
    preposition: with
    triggers:
      - type: response
        data:
          text: You feel a faint tingling transmitted through it.

  - id: touch
    requires:
      - type: flag
        negate: true
        data: { flag: mirror-mung }
    triggers:
      - type: response
        data:
          text: There is a rumble from deep within the earth and the room shakes.
      - type: change-scene
        data: { scene: mirror-room-1 }
