id: trident
name: crystal trident

synonyms:
  - trident
  - fork
  - treasure
  - poseidon trident
  - poseidon fork
  - poseidon treasure
  - own trident
  - own fork
  - own treasure
  - crystal fork
  - crystal treasure
portable: true
size: weight
measures:
  - id: weight
    max: 20
tags: [treasure]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - conditions:
      - type: handled
        negate: true
        data: { object: trident }
    triggers:
      - type: response
        data:
          text: On the shore lies Poseidon's own crystal trident.
  - triggers:
      - type: response
        data:
          text: There is a crystal trident here.
start: atlantis-room
