id: round-room
tags: [dark]

meta:
  title: Round Room

actions:
  - id: look
    requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            This is a circular stone room with passages in all directions. Several of them have
            unfortunately been blocked by cave-ins.
  - id: look
    triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

objects: [large-bag, stiletto, thief]

navigation:
  - id: north
    triggers:
      - type: change-scene
        data:
          scene: ns-passage
  - id: south
    triggers:
      - type: change-scene
        data:
          scene: narrow-passage
  - id: east
    triggers:
      - type: change-scene
        data:
          scene: loud-room
  - id: west
    triggers:
      - type: change-scene
        data:
          scene: ew-passage
  - id: southeast
    triggers:
      - type: change-scene
        data:
          scene: engravings-cave
