id: ns-passage
tags: [dark]

meta:
  title: North-South Passage

actions:
  - id: look
    requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            This is a high north-south passage, which forks to the northeast.
  - id: look
    triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

navigation:
  - id: north
    triggers:
      - type: change-scene
        data:
          scene: chasm-room
  - id: south
    triggers:
      - type: change-scene
        data:
          scene: round-room
  - id: northeast
    triggers:
      - type: change-scene
        data:
          scene: deep-canyon
