id: bar
name: platinum bar

synonyms:
  - bar
  - platinum
  - treasure
  - platinum platinum
  - platinum treasure
  - large bar
  - large platinum
  - large treasure
portable: true
size: weight
measures:
  - id: weight
    max: 20
tags: [treasure]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: On the ground is a large platinum bar.
start: loud-room

actions:
  - id: get
    conditions:
      - type: flag
        negate: true
        data: { flag: loud-flag }
    triggers:
      - type: response
        data:
          text: >-
            You cannot hear yourself think, let alone pick anything up.
