id: grating-room
tags: [dark]

name: Grating Room

presence:
  - requires:
      - type: flag
        data:
          flag: grate-open
    triggers:
      - type: response
        data:
          text: >-
            You are in a small room near the maze. There are twisty passages in the immediate
            vicinity.
      - type: response
        data:
          text: Above you is an open grating with sunlight pouring in.

  - requires:
      - type: flag
        data:
          flag: light
      - type: flag
        data:
          flag: grate-unlocked
    triggers:
      - type: response
        data:
          text: >-
            You are in a small room near the maze. There are twisty passages in the immediate
            vicinity.
      - type: response
        data:
          text: Above you is a grating.

  - requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            You are in a small room near the maze. There are twisty passages in the immediate
            vicinity.
      - type: response
        data:
          text: Above you is a grating locked with a skull-and-crossbones lock.

  - triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

objects:
  - id: grating-room.teeth
    name: set of teeth
    synonyms: [teeth, tooth]
    actions:
      - id: brush
        triggers:
          - type: response
            data:
              text: >-
                Dental hygiene is highly recommended, but I'm not sure what you want to brush
                them with.
  - id: grating-room.wall
    name: surrounding wall
    synonyms: [wall, walls]
    actions:
      - id: look
        triggers:
          - type: response
            data:
              text: The wall is a wall, and gives nothing away.
  - id: grating-room.grate
    name: grating
    synonyms: [grate]
    actions:
      - id: unlock
        requires:
          - type: has-item
            data:
              object: keys
            failure:
              triggers:
                - type: response
                  data:
                    text: You have nothing to unlock it with.
        triggers:
          - type: set-flag
            data:
              flag: grate-unlocked
              value: true
          - type: response
            data:
              text: The grate is unlocked.

      - id: lock
        triggers:
          - type: set-flag
            data:
              flag: grate-unlocked
              value: false
          - type: response
            data:
              text: The grate is locked.

      - id: open
        requires:
          - type: flag
            data:
              flag: grate-unlocked
            failure:
              triggers:
                - type: response
                  data:
                    text: The grating is locked.
          - type: flag
            negate: true
            data:
              flag: grate-open
            failure:
              triggers:
                - type: response
                  data:
                    text: It is already open.
          - type: flag
            negate: true
            data:
              flag: grate-revealed
        triggers:
          - type: response
            data:
              text: The grating opens to reveal trees above you.
          - type: response
            data:
              text: A pile of leaves falls onto your head and to the ground.
          - type: move-object
            data:
              object: leaves
              to: here
          - type: set-flag
            data:
              flag: grate-revealed
              value: true
          - type: set-flag
            data:
              flag: grate-open
              value: true

      - id: open
        requires:
          - type: flag
            data:
              flag: grate-unlocked
            failure:
              triggers:
                - type: response
                  data:
                    text: The grating is locked.
          - type: flag
            negate: true
            data:
              flag: grate-open
            failure:
              triggers:
                - type: response
                  data:
                    text: It is already open.
        triggers:
          - type: response
            data:
              text: The grating opens to reveal trees above you.
          - type: set-flag
            data:
              flag: grate-open
              value: true

      - id: close
        requires:
          - type: flag
            data:
              flag: grate-open
            failure:
              triggers:
                - type: response
                  data:
                    text: It is already closed.
        triggers:
          - type: response
            data:
              text: The grating is closed.
          - type: set-flag
            data:
              flag: grate-open
              value: false

      - id: put
        preposition: in
        indirect: axe
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

      - id: put
        preposition: in
        indirect: timbers
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

      - id: put
        preposition: in
        indirect: coffin
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

      - id: put
        preposition: in
        indirect: leaves
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

      - id: put
        preposition: in
        indirect: sword
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

      - id: put
        preposition: in
        indirect: trunk
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

      - id: put
        preposition: on
        indirect: axe
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

      - id: put
        preposition: on
        indirect: timbers
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

      - id: put
        preposition: on
        indirect: coffin
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

      - id: put
        preposition: on
        indirect: leaves
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

      - id: put
        preposition: on
        indirect: sword
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

      - id: put
        preposition: on
        indirect: trunk
        triggers:
          - type: response
            data:
              text: It won't fit through the grating.

navigation:
  - id: southwest
    triggers:
      - type: change-scene
        data:
          scene: maze-11
  - id: up
    requires:
      - type: flag
        data:
          flag: grate-open
        failure:
          triggers:
            - type: response
              data:
                text: The grating is closed.
    triggers:
      - type: change-scene
        data:
          scene: grating-clearing
