id: chalice

synonyms:
  - cup
  - silver
  - treasure
  - silver chalice
  - silver cup
  - silver silver
  - silver treasure
  - engravings chalice
  - engravings cup
  - engravings silver
  - engravings treasure
portable: true
size: weight
measures:
  - id: weight
    max: 10
tags: [treasure]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: There is a silver chalice, intricately engraved, here.
start: treasure-room

