id: painting

synonyms: [painting, art, canvas, treasure, beauti painting, beauti art, beauti canvas]
portable: true
size: weight
measures:
  - id: weight
    max: 15
tags: [treasure]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - conditions:
      - type: handled
        negate: true
        data: { object: painting }
    triggers:
      - type: response
        data:
          text: >-
            Fortunately, there is still one chance for you to be a vandal, for on the far wall is a painting
            of unparalleled beauty.
  - triggers:
      - type: response
        data:
          text: A painting by a neglected genius is here.
start: gallery

actions:

  - id: break
    once:
      failure:
        triggers:
          - type: response
            data:
              text: There is a worthless piece of canvas here.
    triggers:
      - type: response
        data:
          text: >-
            Congratulations! Unlike the other vandals, who merely stole the artist's masterpieces,
            you have destroyed one.
      - type: set-flag
        data:
          flag: painting-ruined
          value: true

  - id: look
    conditions:
      - type: flag
        data:
          flag: painting-ruined
    triggers:
      - type: response
        data:
          text: There is a worthless piece of canvas here.

  - id: look
    triggers:
      - type: response
        data:
          text: A painting by a neglected genius.
