id: maze-3
tags: [dark]

meta:
  title: Maze

presence:
  - requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: This is part of a maze of twisty little passages, all alike.
  - triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

navigation:
  - id: north
    triggers:
      - type: change-scene
        data:
          scene: maze-4
  - id: west
    triggers:
      - type: change-scene
        data:
          scene: maze-2
  - id: up
    triggers:
      - type: change-scene
        data:
          scene: maze-5
