id: tiny-cave
tags: [dark]

meta:
  title: Cave

actions:
  - id: look
    requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            This is a tiny cave with entrances west and north, and a dark, forbidding staircase
            leading down.
  - id: look
    triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

navigation:
  - id: north
    triggers:
      - type: change-scene
        data:
          scene: mirror-room-2
  - id: west
    triggers:
      - type: change-scene
        data:
          scene: winding-passage
  - id: down
    triggers:
      - type: change-scene
        data:
          scene: entrance-to-hades
