id: land-of-living-dead

name: Land of the Dead

presence:
  - triggers:
      - type: response
        data:
          text: >-
            You have entered the Land of the Living Dead. Thousands of lost souls can be heard
            weeping and moaning. In the corner are stacked the remains of dozens of previous
            adventurers less fortunate than yourself. A passage exits to the north.

objects:
  - id: land-of-living-dead.teeth
    name: set of teeth
    synonyms: [teeth, tooth]
    actions:
      - id: brush
        triggers:
          - type: response
            data:
              text: >-
                Dental hygiene is highly recommended, but I'm not sure what you want to brush
                them with.
  - id: land-of-living-dead.wall
    name: surrounding wall
    synonyms: [wall, walls]
    actions:
      - id: look
        triggers:
          - type: response
            data:
              text: The wall is a wall, and gives nothing away.
  - skull
  - id: land-of-living-dead.bodies
    name: pile of bodies
    synonyms:
      - bodies
      - body
      - remains
      - pile
      - mangled bodies
      - mangled body
      - mangled remains
      - mangled pile

    actions:
      - id: get
        triggers:
          - type: response
            data:
              text: >-
                A force keeps you from taking the bodies.
navigation:
  - id: north
    triggers:
      - type: change-scene
        data:
          scene: entrance-to-hades