id: dam

synonyms: [gate, gates, fcd#3]
start: dam-room

measures:
  - id: water
    max: 8
    start: 8
    thresholds:
      - from: 0
        triggers:
          - type: set-flag
            data:
              flag: low-tide
              value: true
      - from: 1
        triggers:
          - type: set-flag
            data:
              flag: low-tide
              value: false
      - from: 8

actions:
  - id: open
    triggers:
      - type: response
        data:
          text: Sounds reasonable, but this isn't how.

  - id: close
    triggers:
      - type: response
        data:
          text: Sounds reasonable, but this isn't how.

  - id: plug
    preposition: with
    triggers:
      - type: response
        data:
          text: >-
            Do you know how big this dam is? You could only stop a tiny leak with that.

  - id: plug
    triggers:
      - type: response
        data:
          text: Are you the little Dutch boy, then? Sorry, this is a big dam.

  - id: look
    triggers:
      - type: response
        data:
          text: >-
            Flood Control Dam #3, of the Frobozz Magic Dam Company, holding back rather more
            water than looks comfortable.
