id: screwdriver

synonyms:
  - tool
  - tools
  - driver
  - screw screwdriver
  - screw tool
  - screw tools
  - screw driver
portable: true
size: weight
measures:
  - id: weight
    max: 5
tags: [basket-cargo, belongings]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: There is a screwdriver here.
start: maintenance-room
