id: slide-room
tags: [dark]

name: Slide Room

presence:
  - requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            This is a small chamber, which appears to have been part of a coal mine. On the
            south wall of the chamber the letters "Granite Wall" are etched in the rock. To the
            east is a long passage, and there is a steep metal slide twisting downward. To the
            north is a small opening.
  - triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

objects:
  - id: slide-room.granite-wall
    name: granite wall
    synonyms: [granite, granite wall]
    actions:
      - id: look
        triggers:
          - type: response
            data:
              text: |-
                It only SAYS "Granite Wall".
      - id: get
        triggers:
          - type: response
            data:
              text: "The wall isn't granite."
      - id: raise
        triggers:
          - type: response
            data:
              text: "The wall isn't granite."
  - id: slide-room.teeth
    name: set of teeth
    synonyms: [teeth, tooth]
    actions:
      - id: brush
        triggers:
          - type: response
            data:
              text: >-
                Dental hygiene is highly recommended, but I'm not sure what you want to brush
                them with.
  - id: slide-room.wall
    name: surrounding wall
    synonyms: [wall, walls]
    actions:
      - id: look
        triggers:
          - type: response
            data:
              text: The wall is a wall, and gives nothing away.
  - id: slide-room.slide
    name: chute
    synonyms:
      - ramp
      - slide
      - steep chute
      - steep ramp
      - steep slide
      - metal chute
      - metal ramp
      - metal slide
      - twisting chute
      - twisting ramp
      - twisting slide

    actions:
      - id: climb
        triggers:
          - type: response
            data:
              text: >-
                You tumble down the slide.
navigation:
  - id: north
    triggers:
      - type: change-scene
        data:
          scene: mine-entrance
  - id: east
    triggers:
      - type: change-scene
        data:
          scene: cold-passage
  - id: down
    triggers:
      - type: change-scene
        data:
          scene: cellar
