#!/usr/bin/env -S deno run --allow-read
/**
 * Regenerate `scenarios.ts` from `tools/zork1-350-walkthrough.txt`.
 *
 * Reads the walkthrough once, splits it into the same cumulative checkpoints
 * `tools/audit.py` marks with `@checkpoint`, and searches each for a
 * `startedAt` that gets through it without a death (see `harness.ts`'s `seek`
 * for what "gets through" and "seed" mean here). The four checkpoints nest -
 * `torch-secured`'s commands are `post-thief`'s with more appended - so a
 * later one failing to find a seed while an earlier one succeeded means
 * whatever comes between them is the place to look first.
 *
 * Run this again whenever the walkthrough changes, or whenever a game change
 * shifts which turns roll dice - a seed search result is only ever a fact
 * about the exact game and the exact script it was found against.
 *
 * `deno task reseed`, from this directory.
 */
import { died, loadGame, seek, transcript } from './harness.ts';

import type { Played } from './harness.ts';

/** The number after "Your score is" in the last `score` reply, or null if none was given. */
const scoreOf = (played: Played): number | null => {
  const match = transcript(played)
    .map((line) => line.match(/Your score is (\d+)/))
    .findLast((m) => m);

  return match ? Number(match[1]) : null;
};

const WALKTHROUGH = new URL('../zork1-350-walkthrough.txt', import.meta.url).pathname;

interface Checkpoint {
  name: string;
  through: number; // 1-indexed line in the walkthrough, inclusive
  // What "good" means beyond merely surviving. The thief's own random theft
  // can take a treasure worth more than the fight it steals from ever cost -
  // the torch, mid-transit through the mine, leaves the player dark without
  // dying outright - so a checkpoint the rest of a scenario depends on checks
  // for the thing it exists to guarantee, not only for the absence of death.
  ok?: (played: Played) => boolean;
}

// The same four points `tools/audit.py`'s `@checkpoint` markers name, plus the
// diamond - the mine's own puzzle finally paying off is this session's other
// hard-won fidelity point, and worth its own frozen seed rather than folding
// it silently into a longer, unnamed script.
const CHECKPOINTS: ReadonlyArray<Checkpoint> = [
  { name: 'postTroll', through: 35 },
  { name: 'postThief', through: 124 },
  { name: 'torchSecured', through: 157 },
  { name: 'diamondSecured', through: 327, ok: (played) => played.state.objects.locations['diamond'] === 'inventory' },
  // Past the end of the file rather than a line count kept in sync by hand -
  // `commandsThrough` slices, and slicing past the end of an array is the
  // rest of the array, not an error. 350 is this walkthrough's own name for
  // itself: the `score` a few commands before the ending is the one place a
  // silent, partial failure earlier in this much longer script - a treasure
  // never banked, a room never reached - would surface as a number under it.
  { name: 'fullGame', through: 10_000, ok: (played) => scoreOf(played) === 350 },
];

const lines = (await Deno.readTextFile(WALKTHROUGH)).split('\n');

const commandsThrough = (line: number): Array<string> =>
  lines
    .slice(0, line)
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith('@checkpoint'));

const source = await loadGame();

const results: Array<{ name: string; seed: string; commands: Array<string> }> = [];

for (const { name, through, ok } of CHECKPOINTS) {
  const commands = commandsThrough(through);
  const check = (played: Played) => !died(played) && (ok?.(played) ?? true);
  const { seed } = seek(source, commands, check);

  console.log(`${name}: ${commands.length} commands, seed ${seed}`);
  results.push({ name, seed, commands });
}

const quoted = (s: string) => JSON.stringify(s);

const body = results
  .map(
    ({ name, seed, commands }) => `export const ${name}: Scenario = {
  seed: ${quoted(seed)},
  commands: [
${commands.map((c) => `    ${quoted(c)},`).join('\n')}
  ],
};
`,
  )
  .join('\n');

const header = `/**
 * Frozen starting points for the risky stretches of the walkthrough.
 *
 * Generated by \`find-seed.ts\` from \`tools/zork1-350-walkthrough.txt\` - do
 * not hand-edit; run \`deno task reseed\` after changing the walkthrough or
 * anything that moves where its dice land. Each scenario's commands run
 * cleanly (no death) under its own \`seed\` for the game as it stood the
 * moment this file was generated.
 */
export interface Scenario {
  seed: string;
  commands: Array<string>;
}

`;

await Deno.writeTextFile(new URL('./scenarios.ts', import.meta.url), header + body);
console.log('\nwrote scenarios.ts');
