id: bracelet
name: sapphire-encrusted bracelet

synonyms:
  - bracelet
  - jewel
  - sapphire
  - treasure
  - sapphire bracelet
  - sapphire jewel
  - sapphire sapphire
  - sapphire treasure
portable: true
size: weight
measures:
  - id: weight
    max: 10
tags: [treasure]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: There is a sapphire-encrusted bracelet here.
start: gas-room
