id: coal
name: small pile of coal

synonyms: [coal, pile, heap, small coal, small pile, small heap]
portable: true
size: weight
measures:
  - id: weight
    max: 20
tags: [basket-cargo, belongings]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: There is a small pile of coal here.
start: dead-end-5
