id: gunk
name: small piece of vitreous slag

synonyms:
  - gunk
  - piece
  - slag
  - small gunk
  - small piece
  - small slag
  - vitreous gunk
  - vitreous piece
  - vitreous slag
portable: true
size: weight
measures:
  - id: weight
    max: 10
tags: [belongings]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: There is a small piece of vitreous slag here.
start: offstage

actions:
  - id: get
    triggers:
      - type: response
        data:
          text: >-
            The slag was rather insubstantial, and crumbles into dust at your touch.
      - type: remove-object
        data: { object: gunk }

  - id: touch
    triggers:
      - type: response
        data:
          text: >-
            The slag was rather insubstantial, and crumbles into dust at your touch.
      - type: remove-object
        data: { object: gunk }
