id: jade
name: jade figurine

synonyms:
  - figurine
  - treasure
  - exquisite figurine
  - exquisite treasure
  - jade treasure
portable: true
size: weight
measures:
  - id: weight
    max: 10
tags: [treasure]
requires:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: There is an exquisite jade figurine here.
start: bat-room
