id: lowered-basket
name: basket

synonyms: [cage, dumbwaiter, lowered cage, lowered dumbwaiter, lowered basket]
contains: true
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: From the chain is suspended a basket.
start: lower-shaft

actions:
  - id: get
    triggers:
      - type: response
        data:
          text: The cage is securely fastened to the iron chain.

  - id: raise
    triggers:
      - type: response
        data:
          text: The basket is raised to the top of the shaft.
      - type: move-tagged
        data: { tag: basket-cargo, from: in:lowered-basket, to: in:raised-basket }
      - type: move-object
        data: { object: lowered-basket, to: offstage }
      - type: move-object
        data: { object: raised-basket, to: shaft-room }
