id: raised-basket
name: basket

synonyms: [cage, dumbwaiter]
contains: true
requires:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: At the end of the chain is a basket.
start: shaft-room

actions:
  - id: get
    triggers:
      - type: response
        data:
          text: The cage is securely fastened to the iron chain.

  - id: lower
    triggers:
      - type: response
        data:
          text: The basket is lowered to the bottom of the shaft.
      - type: move-tagged
        data: { tag: basket-cargo, from: in:raised-basket, to: in:lowered-basket }
      - type: move-object
        data: { object: raised-basket, to: offstage }
      - type: move-object
        data: { object: lowered-basket, to: lower-shaft }
