id: timbers
name: broken timber

synonyms:
  - timbers
  - pile
  - wooden timbers
  - wooden pile
  - broken timbers
  - broken pile
portable: true
size: weight
measures:
  - id: weight
    max: 50
tags: [belongings]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: There is a broken timber here.
start: timber-room
