id: leaves
name: pile of leaves

synonyms: [leaves, leaf, pile]
portable: true
size: weight
measures:
  - id: weight
    max: 25
tags: [belongings]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: On the ground is a pile of leaves.
start: grating-clearing

actions:
  - id: count
    triggers:
      - type: response
        data:
          text: There are 69,105 leaves here.

  - id: burn
    conditions:
      - type: has-item
        data:
          object: leaves
    triggers:
      - type: response
        data:
          text: The leaves burn, and so do you.
      - type: set-flag
        data:
          flag: player-died
          value: true

  - id: burn
    triggers:
      - type: response
        data:
          text: The leaves burn.
      - type: set-flag
        data:
          flag: grate-revealed
          value: true
      - type: remove-object
        data:
          object: leaves

  - id: cut
    triggers:
      - type: response
        data:
          text: You rustle the leaves around, making quite a mess.
      - type: set-flag
        data:
          flag: grate-revealed
          value: true

  - id: move
    conditions:
      - type: flag
        negate: true
        data:
          flag: grate-revealed
    triggers:
      - type: response
        data:
          text: 'Done.'
      - type: response
        data:
          text: In disturbing the pile of leaves, a grating is revealed.
      - type: set-flag
        data:
          flag: grate-revealed
          value: true

  - id: move
    triggers:
      - type: response
        data:
          text: 'Done.'

  - id: get
    conditions:
      - type: flag
        negate: true
        data:
          flag: grate-revealed
    triggers:
      - type: response
        data:
          text: In disturbing the pile of leaves, a grating is revealed.
      - type: set-flag
        data:
          flag: grate-revealed
          value: true
      - type: add-to-inventory
        data:
          object: leaves
          announce: true

  - id: look
    preposition: under
    conditions:
      - type: flag
        negate: true
        data:
          flag: grate-revealed
    triggers:
      - type: response
        data:
          text: >-
            Underneath the pile of leaves is a grating. As you release the leaves, the grating
            is once again concealed from view.

  - id: look
    preposition: under
    triggers:
      - type: response
        data:
          text: There is nothing but dust there.
