id: mailbox
name: small mailbox

synonyms: [mailbox, box, small box]
contains: true
requires:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: There is a small mailbox here.
start: west-of-house

actions:
  - id: get
    triggers:
      - type: response
        data: { text: It is securely anchored. }
  - id: open
    triggers:
      - type: response
        data:
          text: >-
            Opening the small mailbox reveals a leaflet.

  - id: close
    triggers:
      - type: response
        data:
          text: >-
            Closed.
