id: nest
name: bird's nest

synonyms: [nest, birds nest]
portable: true
size: weight
measures:
  - id: weight
    max: 5
contains: true
tags: [belongings]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - conditions:
      - type: handled
        negate: true
        data: { object: nest }
      - type: object-in
        data:
          object: egg
          location: in:nest
    triggers:
      - type: response
        data:
          text: Beside you on the branch is a small bird's nest.
      - type: response
        data:
          text: >-
            In the bird's nest is a large egg encrusted with precious jewels, apparently
            scavenged by a childless songbird. The egg is covered with fine gold inlay, and
            ornamented in lapis lazuli and mother-of-pearl. Unlike most eggs, this one is hinged
            and closed with a delicate looking clasp. The egg appears extremely fragile.
  - conditions:
      - type: handled
        negate: true
        data: { object: nest }
    triggers:
      - type: response
        data:
          text: Beside you on the branch is a small bird's nest.
  - conditions:
      - type: object-in
        data:
          object: egg
          location: in:nest
    triggers:
      - type: response
        data:
          text: There is a bird's nest here.
      - type: response
        data:
          text: >-
            In the bird's nest is a large egg encrusted with precious jewels, apparently
            scavenged by a childless songbird. The egg is covered with fine gold inlay, and
            ornamented in lapis lazuli and mother-of-pearl. Unlike most eggs, this one is hinged
            and closed with a delicate looking clasp. The egg appears extremely fragile.
  - triggers:
      - type: response
        data:
          text: There is a bird's nest here.
start: up-a-tree

actions:
  - id: drop
    conditions:
      - type: scene
        data:
          id: up-a-tree
      - type: object-in
        data:
          object: egg
          location: in:nest
    triggers:
      - type: response
        data:
          text: >-
            The nest falls to the ground, and the egg spills out of it, seriously damaged.
      - type: move-object
        data:
          object: nest
          to: here
      - type: remove-object
        data:
          object: egg
      - type: move-object
        data:
          object: broken-egg
          to: path
  - id: open
    triggers:
      - type: response
        data:
          text: >-
            Opening the bird's nest reveals a jewel-encrusted egg.

  - id: close
    triggers:
      - type: response
        data:
          text: >-
            Closed.
