id: boat-label
name: tan label

synonyms:
  - label
  - fineprint
  - print
  - tan fineprint
  - tan print
  - fine label
  - fine fineprint
  - fine print
portable: true
size: weight
measures:
  - id: weight
    max: 2
tags: [belongings]
requires:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: There is a tan label here.
start: in:inflated-boat

actions:
  - id: look
    triggers:
      - type: response
        data:
          text: |-
            !!!!FROBOZZ MAGIC BOAT COMPANY!!!!

            Hello, Sailor!

            Instructions for use:

            To get into a body of water, say "Launch".
            To get to shore, say "Land" or the direction in which you want to maneuver the boat.

            Warranty:

            This boat is guaranteed against all defects for a period of 76 milliseconds from date of purchase or until first used, whichever comes first.

            Warning:
            This boat is made of thin plastic.
            Good Luck!
