id: emerald
name: large emerald

synonyms: [emerald, treasure, large treasure]
portable: true
size: weight
measures:
  - id: weight
    max: 5
tags: [treasure]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: There is a large emerald here.
start: in:buoy
