id: pot-of-gold
name: pot of gold

synonyms: [pot, gold, treasure, gold pot, gold gold, gold treasure]
portable: true
size: weight
measures:
  - id: weight
    max: 15
tags: [treasure]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
  - type: flag
    data: { flag: rainbow-flag }
presence:
  - conditions:
      - type: handled
        negate: true
        data: { object: pot-of-gold }
    triggers:
      - type: response
        data:
          text: At the end of the rainbow is a pot of gold.
  - triggers:
      - type: response
        data:
          text: There is a pot of gold here.
start: end-of-rainbow
