id: shovel

synonyms: [tool, tools]
portable: true
size: weight
measures:
  - id: weight
    max: 15
tags: [belongings]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: There is a shovel here.
start: sandy-beach
