id: treasure-room
tags: [dark]

meta:
  title: Treasure Room

presence:
  - requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            This is a large room, whose east wall is solid granite. A number of discarded bags,
            which crumble at your touch, are scattered about on the floor. There is an exit down
            a staircase.
  - triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

objects: [chalice]

navigation:
  - id: down
    triggers:
      - type: change-scene
        data:
          scene: cyclops-room
