id: south-temple

name: Altar

presence:
  - conditions:
      - type: object-in
        data:
          object: book
          location: in:altar
    triggers:
      - type: response
        data:
          text: >-
            This is the south end of a large temple. In front of you is what appears to be an
            altar. In one corner is a small hole in the floor which leads into darkness. You
            probably could not get back up it.
      - type: response
        data:
          text: >-
            On the altar is a large black book, open to page 569.

  - triggers:
      - type: response
        data:
          text: >-
            This is the south end of a large temple. In front of you is what appears to be an
            altar. In one corner is a small hole in the floor which leads into darkness. You
            probably could not get back up it.

actions:
  - id: pray
    triggers:
      - type: change-scene
        data:
          scene: forest-1

objects:
  - altar
  - book
  - candles
  - id: south-temple.teeth
    name: set of teeth
    synonyms: [teeth, tooth]
    actions:
      - id: brush
        triggers:
          - type: response
            data:
              text: >-
                Dental hygiene is highly recommended, but I'm not sure what you want to brush
                them with.
  - id: south-temple.wall
    name: surrounding wall
    synonyms: [wall, walls]
    actions:
      - id: look
        triggers:
          - type: response
            data:
              text: The wall is a wall, and gives nothing away.
navigation:
  - id: north
    triggers:
      - type: change-scene
        data:
          scene: north-temple
  - id: down
    conditions:
      - type: has-item
        negate: true
        data:
          object: coffin
        failure:
          triggers:
            - type: response
              data:
                text: You haven't a prayer of getting the coffin down there.
    triggers:
      - type: change-scene
        data:
          scene: tiny-cave
