id: mine-entrance
tags: [dark]

meta:
  title: Mine Entrance

actions:
  - id: look
    requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            You are standing at the entrance of what might have been a coal mine. The shaft
            enters the west wall, and there is another exit on the south end of the room.
  - id: look
    triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

navigation:
  - id: south
    triggers:
      - type: change-scene
        data:
          scene: slide-room
  - id: west
    triggers:
      - type: change-scene
        data:
          scene: squeeky-room