id: reservoir-north
tags: [dark]

name: Reservoir North

presence:
  - requires:
      - type: flag
        data:
          flag: light
      - type: flag
        data:
          flag: gates-open
      - type: flag
        data:
          flag: low-tide
    triggers:
      - type: response
        data:
          text: >-
            You are in a large cavernous room, the south of which was formerly a lake. However,
            with the water level lowered, there is merely a wide stream running through there.
      - type: response
        data:
          text: >-
            There is a slimy stairway leaving the room to the north.
  - requires:
      - type: flag
        data:
          flag: light
      - type: flag
        data:
          flag: gates-open
      - type: flag
        negate: true
        data:
          flag: low-tide
    triggers:
      - type: response
        data:
          text: >-
            You are in a large cavernous area. To the south is a wide lake, whose water level
            appears to be falling rapidly.
      - type: response
        data:
          text: >-
            There is a slimy stairway leaving the room to the north.
  - requires:
      - type: flag
        data:
          flag: light
      - type: flag
        negate: true
        data:
          flag: gates-open
      - type: flag
        data:
          flag: low-tide
    triggers:
      - type: response
        data:
          text: >-
            You are in a cavernous area, to the south of which is a very wide stream. The level
            of the stream is rising rapidly, and it appears that before long it will be
            impossible to cross to the other side.
      - type: response
        data:
          text: >-
            There is a slimy stairway leaving the room to the north.
  - requires:
      - type: flag
        data:
          flag: light
      - type: flag
        negate: true
        data:
          flag: gates-open
      - type: flag
        negate: true
        data:
          flag: low-tide
    triggers:
      - type: response
        data:
          text: >-
            You are in a large cavernous room, north of a large lake.
      - type: response
        data:
          text: >-
            There is a slimy stairway leaving the room to the north.
  - triggers:
      - type: response
        data:
          text: >-
            It is pitch black. You are likely to be eaten by a grue.

objects:
  - id: reservoir-north.teeth
    name: set of teeth
    synonyms: [teeth, tooth]
    actions:
      - id: brush
        triggers:
          - type: response
            data:
              text: >-
                Dental hygiene is highly recommended, but I'm not sure what you want to brush
                them with.
  - id: reservoir-north.wall
    name: surrounding wall
    synonyms: [wall, walls]
    actions:
      - id: look
        triggers:
          - type: response
            data:
              text: The wall is a wall, and gives nothing away.
  - id: reservoir-north.lake
    name: lake
    synonyms: [lake]
    actions:
      - id: cross
        requires:
          - type: flag
            data: { flag: low-tide }
        triggers:
          - type: response
            data:
              text: "There's not much lake left...."
      - id: swim
        requires:
          - type: flag
            data: { flag: low-tide }
        triggers:
          - type: response
            data:
              text: "There's not much lake left...."
      - id: cross
        triggers:
          - type: response
            data:
              text: "It's too wide to cross."
      - id: swim
        triggers:
          - type: response
            data:
              text: "You can't swim in this lake."
  - pump
  - id: reservoir-north.global-water
    name: water
    synonyms: [quantity]

    actions:
      - id: get
        triggers:
          - type: response
            data:
              text: >-
                The water slips through your fingers.
      - id: drink
        triggers:
          - type: response
            data:
              text: >-
                Thank you very much. I was rather thirsty.
navigation:
  - id: north
    triggers:
      - type: change-scene
        data:
          scene: atlantis-room
  - id: south
    requires:
      - type: flag
        data:
          flag: low-tide
        failure:
          triggers:
            - type: response
              data:
                text: You would drown.
    triggers:
      - type: change-scene
        data:
          scene: reservoir
