id: altar
contains: true
start: south-temple

actions:
  - id: look
    preposition: 'on'
    requires:
      - type: object-in
        data:
          object: book
          location: in:altar
    triggers:
      - type: response
        data:
          text: On the altar is a large black book, open to page 569.

  - id: look
    triggers:
      - type: response
        data:
          text: >-
            A broad slab of stone, worn smooth in the middle by a great many hands and a great
            many years.
  - id: open
    triggers:
      - type: response
        data:
          text: >-
            Opening the altar reveals a black book.

  - id: close
    triggers:
      - type: response
        data:
          text: >-
            Closed.
