id: torch

synonyms:
  - ivory
  - treasure
  - flaming torch
  - flaming ivory
  - flaming treasure
  - ivory torch
  - ivory ivory
  - ivory treasure
portable: true
size: weight
measures:
  - id: weight
    max: 20
tags: [treasure, basket-cargo]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - conditions:
      - type: handled
        negate: true
        data: { object: torch }
    triggers:
      - type: response
        data:
          text: Sitting on the pedestal is a flaming torch, made of ivory.
  - triggers:
      - type: response
        data:
          text: There is a torch here.
start: in:pedestal

actions:
  - id: look
    triggers:
      - type: response
        data: { text: The torch is burning. }

  - id: pour
    triggers:
      - type: response
        data: { text: The water evaporates before it gets close. }

  - id: extinguish
    triggers:
      - type: response
        data: { text: You nearly burn your hand trying to extinguish the flame. }
