id: engravings-cave
tags: [dark]

meta:
  title: Engravings Cave

presence:
  - requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            You have entered a low cave with passages leading northwest and east.
  - triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

objects: [engravings]

navigation:
  - id: east
    triggers:
      - type: change-scene
        data:
          scene: dome-room
  - id: northwest
    triggers:
      - type: change-scene
        data:
          scene: round-room
