id: knife
name: nasty knife

synonyms:
  - knives
  - knife
  - blade
  - nasty knives
  - nasty blade
  - unrusty knives
  - unrusty knife
  - unrusty blade
portable: true
size: weight
measures:
  - id: weight
    max: 5
tags: [belongings]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - conditions:
      - type: handled
        negate: true
        data: { object: knife }
    triggers:
      - type: response
        data:
          text: On a table is a nasty-looking knife.
  - triggers:
      - type: response
        data:
          text: There is a nasty knife here.
start: in:attic-table

actions:
  - id: drop
    conditions:
      - type: flag
        data: { flag: aboard }
      - type: any-of
        data:
          conditions:
            - type: scene
              data: { id: reservoir }
            - type: scene
              data: { id: in-stream }
    triggers:
      - type: response
        data:
          text: >-
            It seems that the nasty knife didn't agree with the boat, as evidenced by the loud hissing
            noise issuing therefrom. With a pathetic sputter, the boat deflates, leaving you without.
      - type: move-object
        data: { object: inflated-boat, to: offstage }
      - type: move-object
        data: { object: punctured-boat, to: here }
      - type: response
        data:
          text: >-
            Another pathetic sputter, this time from you, heralds your drowning.
      - type: set-flag
        data: { flag: player-died, value: true }

  - id: drop
    conditions:
      - type: flag
        data: { flag: aboard }
      - type: scene
        data: { tag: river }
    triggers:
      - type: response
        data:
          text: >-
            It seems that the nasty knife didn't agree with the boat, as evidenced by the loud hissing
            noise issuing therefrom. With a pathetic sputter, the boat deflates, leaving you without.
      - type: move-object
        data: { object: inflated-boat, to: offstage }
      - type: move-object
        data: { object: punctured-boat, to: here }
      - type: response
        data:
          text: >-
            In other words, fighting the fierce currents of the Frigid River. You manage to hold your own
            for a bit, but then you are carried over a waterfall and into some nasty rocks. Ouch!
      - type: set-flag
        data: { flag: player-died, value: true }

  - id: drop
    conditions:
      - type: flag
        data: { flag: aboard }
    triggers:
      - type: response
        data:
          text: >-
            It seems that the nasty knife didn't agree with the boat, as evidenced by the loud hissing
            noise issuing therefrom. With a pathetic sputter, the boat deflates, leaving you without.
      - type: move-object
        data: { object: inflated-boat, to: offstage }
      - type: move-object
        data: { object: punctured-boat, to: here }
      - type: set-flag
        data: { flag: aboard, value: false }

  - id: look
    triggers:
      - type: response
        data:
          text: A nasty-looking knife, of the sort a person might regret meeting.
