id: lamp
name: brass lantern

synonyms: [lamp, lantern, light, brass lamp, brass light]
portable: true
size: weight
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - conditions:
      - type: handled
        negate: true
        data: { object: lamp }
    triggers:
      - type: response
        data:
          text: A battery-powered brass lantern is on the trophy case.
  - triggers:
      - type: response
        data:
          text: There is a brass lantern (battery-powered) here.
start: living-room

measures:
  - id: life
    max: 392
    start: 392
    thresholds:
      - from: 0
        triggers:
          - type: response
            data:
              text: The lamp has burned out.
          - type: set-flag
            data:
              flag: lamp-on
              value: false
          - type: set-flag
            data:
              flag: lamp-burned-out
              value: true
          - type: set-flag
            data:
              flag: light
              value: false
      - from: 1
        triggers:
          - type: response
            data:
              text: The lamp is nearly out.
      - from: 15
        triggers:
          - type: response
            data:
              text: The lamp is definitely dimmer now.
      - from: 85
        triggers:
          - type: response
            data:
              text: The lamp appears a bit dimmer.
      - from: 185
  - id: weight
    max: 15

actions:
  - id: turn
    preposition: 'on'
    conditions:
      - type: flag
        negate: true
        data:
          flag: lamp-burned-out
        failure:
          triggers:
            - type: response
              data:
                text: A burned-out lamp won't light.
      - type: flag
        negate: true
        data:
          flag: lamp-on
        failure:
          triggers:
            - type: response
              data:
                text: It is already on.
    triggers:
      - type: response
        data:
          text: The brass lantern is now on.
      - type: set-flag
        data:
          flag: lamp-on
          value: true
      - type: set-flag
        data:
          flag: light
          value: true

  - id: turn
    preposition: 'off'
    conditions:
      - type: flag
        data:
          flag: lamp-on
        failure:
          triggers:
            - type: response
              data:
                text: It is already off.
    triggers:
      - type: response
        data:
          text: The brass lantern is now off.
      - type: set-flag
        data:
          flag: lamp-on
          value: false
      - type: set-flag
        data:
          flag: light
          value: false

  - id: burn
    conditions:
      - type: flag
        negate: true
        data:
          flag: lamp-burned-out
        failure:
          triggers:
            - type: response
              data:
                text: A burned-out lamp won't light.
      - type: flag
        negate: true
        data:
          flag: lamp-on
        failure:
          triggers:
            - type: response
              data:
                text: It is already on.
    triggers:
      - type: response
        data:
          text: The brass lantern is now on.
      - type: set-flag
        data:
          flag: lamp-on
          value: true
      - type: set-flag
        data:
          flag: light
          value: true

  - id: extinguish
    conditions:
      - type: flag
        data:
          flag: lamp-on
        failure:
          triggers:
            - type: response
              data:
                text: It is already off.
    triggers:
      - type: response
        data:
          text: The brass lantern is now off.
      - type: set-flag
        data:
          flag: lamp-on
          value: false
      - type: set-flag
        data:
          flag: light
          value: false

  - id: look
    conditions:
      - type: flag
        data:
          flag: lamp-burned-out
    triggers:
      - type: response
        data:
          text: The lamp has burned out.

  - id: look
    conditions:
      - type: flag
        data:
          flag: lamp-on
    triggers:
      - type: response
        data:
          text: The lamp is on.

  - id: look
    triggers:
      - type: response
        data:
          text: The lamp is turned off.
