id: lunch

synonyms:
  - food
  - sandwich
  - dinner
  - hot food
  - hot sandwich
  - hot lunch
  - hot dinner
  - pepper food
  - pepper sandwich
  - pepper lunch
  - pepper dinner
portable: true
size: weight
measures:
  - id: weight
    max: 5
tags: [belongings]
requires:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: A hot pepper sandwich is here.
start: in:sandwich-bag
