id: trap-door
name: trap door

synonyms:
  - door
  - trapdoor
  - trap
  - trap door
  - trap-door
  - cover
  - trap trapdoor
  - trap trap-door
  - trap cover
  - dusty door
  - dusty trapdoor
  - dusty trap-door
  - dusty cover
start: living-room

conditions:
  - type: flag
    data:
      flag: rug-moved

actions:
  - id: open
    conditions:
      - type: flag
        data:
          flag: trap-door-open
        negate: true
    triggers:
      - type: response
        data:
          text: >-
            The door reluctantly opens to reveal a rickety staircase descending into darkness.
      - type: set-flag
        data:
          flag: trap-door-open
          value: true

  - id: open
    conditions:
      - type: chance
        data: { name: dummy-open, of: 3, index: 1 }
    triggers:
      - type: response
        data:
          text: Look around.

  - id: open
    conditions:
      - type: chance
        data: { name: dummy-open, of: 3, index: 2 }
    triggers:
      - type: response
        data:
          text: Too late for that.

  - id: open
    triggers:
      - type: response
        data:
          text: Have your eyes checked.

  - id: close
    conditions:
      - type: flag
        data:
          flag: trap-door-open
    triggers:
      - type: response
        data:
          text: The door swings shut and closes.
      - type: set-flag
        data:
          flag: trap-door-open
          value: false

  - id: close
    conditions:
      - type: chance
        data: { name: dummy-close, of: 3, index: 1 }
    triggers:
      - type: response
        data:
          text: Look around.

  - id: close
    conditions:
      - type: chance
        data: { name: dummy-close, of: 3, index: 2 }
    triggers:
      - type: response
        data:
          text: Too late for that.

  - id: close
    triggers:
      - type: response
        data:
          text: Have your eyes checked.

  - id: look
    preposition: under
    conditions:
      - type: flag
        data:
          flag: trap-door-open
    triggers:
      - type: response
        data:
          text: You see a rickety staircase descending into darkness.

  - id: look
    preposition: under
    triggers:
      - type: response
        data:
          text: It's closed.
