id: maintenance-room
tags: [dark]

name: Maintenance Room

presence:
  - conditions:
      - type: flag
        data:
          flag: maintenance-lights
    triggers:
      - type: response
        data:
          text: >-
            This is what appears to have been the maintenance room for Flood Control Dam #3.
            Apparently, this room has been ransacked recently, for most of the valuable
            equipment is gone. On the wall in front of you is a group of buttons colored blue,
            yellow, brown, and red. There are doorways to the west and south.
  - conditions:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            This is what appears to have been the maintenance room for Flood Control Dam #3.
            Apparently, this room has been ransacked recently, for most of the valuable
            equipment is gone. On the wall in front of you is a group of buttons colored blue,
            yellow, brown, and red. There are doorways to the west and south.
  - triggers:
      - type: response
        data:
          text: >-
            It is pitch black. You are likely to be eaten by a grue.

objects:
  - id: maintenance-room.teeth
    name: set of teeth
    synonyms: [teeth, tooth]
    actions:
      - id: brush
        triggers:
          - type: response
            data:
              text: >-
                Dental hygiene is highly recommended, but I'm not sure what you want to brush
                them with.
  - id: maintenance-room.wall
    name: surrounding wall
    synonyms: [wall, walls]
    actions:
      - id: look
        triggers:
          - type: response
            data:
              text: The wall is a wall, and gives nothing away.
  - tool-chest
  - yellow-button
  - brown-button
  - red-button
  - blue-button
  - leak
  - screwdriver
  - tube
  - putty
  - wrench

navigation:
  - id: south
    triggers:
      - type: change-scene
        data:
          scene: dam-lobby
  - id: west
    triggers:
      - type: change-scene
        data:
          scene: dam-lobby
