id: small-cave
tags: [dark]

meta:
  title: Cave

presence:
  - requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            This is a tiny cave with entrances west and north, and a staircase leading down.
  - triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

navigation:
  - id: north
    triggers:
      - type: change-scene
        data:
          scene: mirror-room-1
  - id: south
    triggers:
      - type: change-scene
        data:
          scene: atlantis-room
  - id: west
    triggers:
      - type: change-scene
        data:
          scene: twisting-passage
  - id: down
    triggers:
      - type: change-scene
        data:
          scene: atlantis-room
