id: dam-lobby

name: Dam Lobby

presence:
  - triggers:
      - type: response
        data:
          text: >-
            This room appears to have been the waiting room for groups touring the dam. There
            are open doorways here to the north and east marked "Private", and there is a path
            leading south over the top of the dam.

objects:
  - match
  - guide
  - id: dam-lobby.teeth
    name: set of teeth
    synonyms: [teeth, tooth]
    actions:
      - id: brush
        triggers:
          - type: response
            data:
              text: >-
                Dental hygiene is highly recommended, but I'm not sure what you want to brush
                them with.
  - id: dam-lobby.wall
    name: surrounding wall
    synonyms: [wall, walls]
    actions:
      - id: look
        triggers:
          - type: response
            data:
              text: The wall is a wall, and gives nothing away.
navigation:
  - id: north
    triggers:
      - type: change-scene
        data:
          scene: maintenance-room
  - id: south
    triggers:
      - type: change-scene
        data:
          scene: dam-room
  - id: east
    triggers:
      - type: change-scene
        data:
          scene: maintenance-room
