id: lower-shaft
tags: [dark]

meta:
  title: Drafty Room

actions:
  - id: look
    requires:
      - type: flag
        data:
          flag: light
      - type: object-in
        data:
          object: lowered-basket
          location: lower-shaft
    triggers:
      - type: response
        data:
          text: >-
            This is a small drafty room in which is the bottom of a long shaft. To the south is
            a passageway and to the east a very narrow passage. In the shaft can be seen a heavy
            iron chain.
      - type: response
        data:
          text: From the chain is suspended a basket.
  - id: look
    requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            This is a small drafty room in which is the bottom of a long shaft. To the south is
            a passageway and to the east a very narrow passage. In the shaft can be seen a heavy
            iron chain.
  - id: look
    triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

objects: [lowered-basket]

navigation:
  - id: south
    triggers:
      - type: change-scene
        data:
          scene: machine-room
  - id: east
    requires:
      - type: flag
        data:
          flag: empty-handed
        failure:
          triggers:
            - type: response
              data:
                text: You cannot fit through this passage with that load.
    triggers:
      - type: change-scene
        data:
          scene: timber-room