id: cold-passage
tags: [dark]

meta:
  title: Cold Passage

actions:
  - id: look
    requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: >-
            This is a cold and damp corridor where a long east-west passageway turns into a
            southward path.
  - id: look
    triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

navigation:
  - id: south
    triggers:
      - type: change-scene
        data:
          scene: mirror-room-1
  - id: west
    triggers:
      - type: change-scene
        data:
          scene: slide-room
