id: bat

synonyms: [vampire, vampire bat, vampire vampire, deranged bat, deranged vampire]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: >-
            In the corner of the room on the ceiling is a large vampire bat who is obviously
            deranged and holding his nose.

start: bat-room

actions:
  - id: look
    triggers:
      - type: response
        data:
          text: >-
            A large vampire bat, hanging from the ceiling, holding his nose against the smell
            of what you are carrying.

  - id: get
    conditions:
      - type: has-item
        negate: true
        data: { object: garlic }
    triggers:
      - type: response
        data:
          text: The bat grabs you by the scruff of your neck and lifts you away.

  - id: get
    triggers:
      - type: response
        data:
          text: You can't reach him; he's on the ceiling.

  - id: attack
    conditions:
      - type: has-item
        negate: true
        data: { object: garlic }
    triggers:
      - type: response
        data:
          text: The bat grabs you by the scruff of your neck and lifts you away.

  - id: attack
    triggers:
      - type: response
        data:
          text: You can't reach him; he's on the ceiling.

  - id: tell
    triggers:
      - type: response
        data:
          text: "    Fweep!\n    Fweep!\n    Fweep!"

  - id: hello
    triggers:
      - type: response
        data:
          text: The bat bows his head to you in greeting.
