id: thief

synonyms:
  - robber
  - man
  - person
  - shady thief
  - shady robber
  - shady man
  - shady person
  - suspicious thief
  - suspicious robber
  - suspicious man
  - suspicious person
  - seedy thief
  - seedy robber
  - seedy man
  - seedy person
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: >-
            There is a suspicious-looking individual, holding a large bag, leaning against one wall. He is
            armed with a deadly stiletto.
start: round-room

holds: [large-bag, stiletto]

measures:
  - id: strength
    max: 5
    start: 5
    thresholds:
      - from: 0
        triggers:
          - type: response
            data:
              text: >-
                Almost as soon as the thief breathes his last breath, a cloud of sinister black
                fog envelops him, and when the fog lifts, the carcass has disappeared.
          - type: remove-object
            data:
              object: thief
          - type: achievement
            data: { id: caught-the-thief }
          - type: move-object
            data:
              object: large-bag
              to: here
          - type: move-object
            data:
              object: stiletto
              to: here
          - type: move-tagged
            data:
              tag: treasure
              from: held:thief
              to: here
          - type: set-flag
            data:
              flag: thief-fighting
              value: false
          - type: set-flag
            data:
              flag: thief-just-died
              value: true
      - from: 1

actions:
  - id: look
    triggers:
      - type: response
        data:
          text: >-
            The thief is a slippery character with beady eyes that flit back and forth. He
            carries, along with an unmistakable arrogance, a large bag over his shoulder and a
            vicious stiletto, whose blade is aimed menacingly in your direction. I'd watch out
            if I were you.

  - id: tell
    triggers:
      - type: response
        data:
          text: The thief is a strong, silent type.

  - id: listen
    triggers:
      - type: response
        data:
          text: The thief says nothing, as you have not been formally introduced.

  - id: get
    triggers:
      - type: response
        data:
          text: Once you got him, what would you do with him?

  - id: give
    indirect: egg
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            jewel-encrusted egg and stops to admire its beauty.
      - type: move-object
        data:
          object: egg
          to: held:thief

  - id: give
    indirect: bag-of-coins
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            leather bag of coins and stops to admire its beauty.
      - type: move-object
        data:
          object: bag-of-coins
          to: held:thief

  - id: give
    indirect: bar
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            platinum bar and stops to admire its beauty.
      - type: move-object
        data:
          object: bar
          to: held:thief

  - id: give
    indirect: bauble
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            beautiful brass bauble and stops to admire its beauty.
      - type: move-object
        data:
          object: bauble
          to: held:thief

  - id: give
    indirect: bracelet
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            sapphire-encrusted bracelet and stops to admire its beauty.
      - type: move-object
        data:
          object: bracelet
          to: held:thief

  - id: give
    indirect: broken-canary
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            broken clockwork canary and stops to admire its beauty.
      - type: move-object
        data:
          object: broken-canary
          to: held:thief

  - id: give
    indirect: broken-egg
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            broken jewel-encrusted egg and stops to admire its beauty.
      - type: move-object
        data:
          object: broken-egg
          to: held:thief

  - id: give
    indirect: canary
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            golden clockwork canary and stops to admire its beauty.
      - type: move-object
        data:
          object: canary
          to: held:thief

  - id: give
    indirect: chalice
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            chalice and stops to admire its beauty.
      - type: move-object
        data:
          object: chalice
          to: held:thief

  - id: give
    indirect: coffin
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            gold coffin and stops to admire its beauty.
      - type: move-object
        data:
          object: coffin
          to: held:thief

  - id: give
    indirect: diamond
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            huge diamond and stops to admire its beauty.
      - type: move-object
        data:
          object: diamond
          to: held:thief

  - id: give
    indirect: emerald
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            large emerald and stops to admire its beauty.
      - type: move-object
        data:
          object: emerald
          to: held:thief

  - id: give
    indirect: jade
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            jade figurine and stops to admire its beauty.
      - type: move-object
        data:
          object: jade
          to: held:thief

  - id: give
    indirect: painting
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            painting and stops to admire its beauty.
      - type: move-object
        data:
          object: painting
          to: held:thief

  - id: give
    indirect: pot-of-gold
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            pot of gold and stops to admire its beauty.
      - type: move-object
        data:
          object: pot-of-gold
          to: held:thief

  - id: give
    indirect: scarab
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            beautiful jeweled scarab and stops to admire its beauty.
      - type: move-object
        data:
          object: scarab
          to: held:thief

  - id: give
    indirect: sceptre
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            sceptre and stops to admire its beauty.
      - type: move-object
        data:
          object: sceptre
          to: held:thief

  - id: give
    indirect: skull
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            crystal skull and stops to admire its beauty.
      - type: move-object
        data:
          object: skull
          to: held:thief

  - id: give
    indirect: torch
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            torch and stops to admire its beauty.
      - type: move-object
        data:
          object: torch
          to: held:thief

  - id: give
    indirect: trident
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            crystal trident and stops to admire its beauty.
      - type: move-object
        data:
          object: trident
          to: held:thief

  - id: give
    indirect: trunk
    triggers:
      - type: response
        data:
          text: >-
            The thief is taken aback by your unexpected generosity, but accepts the
            trunk of jewels and stops to admire its beauty.
      - type: move-object
        data:
          object: trunk
          to: held:thief

  - id: give
    triggers:
      - type: response
        data:
          text: >-
            The thief places the gift in his bag and thanks you politely.

  - id: attack
    preposition: with
    indirect: knife
    conditions:
      - type: has-item
        data:
          object: knife
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the knife.
      - type: measure
        data:
          subject: thief
          measure: strength
          max: 1
      - type: chance
        data:
          of: 100
          index: [1..40]
          name: characters-thief-character-143
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your knife misses the thief by an inch.
    triggers:
      - type: response
        data:
          text: The fatal blow catches the thief squarely, and he crumples to the floor.
      - type: adjust-measure
        data:
          subject: thief
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: knife
    conditions:
      - type: has-item
        data:
          object: knife
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the knife.
      - type: chance
        data:
          of: 100
          index: [1..40]
          name: characters-thief-character-172
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your knife misses the thief by an inch.
    triggers:
      - type: response
        data:
          text: A quick thrust pinks the thief's arm, and blood starts to trickle down.
      - type: adjust-measure
        data:
          subject: thief
          measure: strength
          by: -1
      - type: set-flag
        data:
          flag: thief-fighting
          value: true

  - id: throw
    indirect: knife
    conditions:
      - type: flag
        negate: true
        data:
          flag: thief-fighting
    triggers:
      - type: response
        data:
          text: >-
            You missed. The thief makes no attempt to take the knife, though it would be a fine
            addition to the collection in his bag. He does seem angered by your attempt.
      - type: move-object
        data:
          object: knife
          to: here
      - type: set-flag
        data:
          flag: thief-fighting
          value: true

  - id: attack
    preposition: with
    indirect: sword
    conditions:
      - type: has-item
        data:
          object: sword
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the sword.
      - type: measure
        data:
          subject: thief
          measure: strength
          max: 1
      - type: chance
        data:
          of: 100
          index: [1..25]
          name: characters-thief-character-sword-1
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your sword misses the thief by an inch.
    triggers:
      - type: response
        data:
          text: The fatal blow catches the thief squarely, and he crumples to the floor.
      - type: adjust-measure
        data:
          subject: thief
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: sword
    conditions:
      - type: has-item
        data:
          object: sword
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the sword.
      - type: chance
        data:
          of: 100
          index: [1..25]
          name: characters-thief-character-sword-2
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your sword misses the thief by an inch.
    triggers:
      - type: response
        data:
          text: A quick thrust pinks the thief's arm, and blood starts to trickle down.
      - type: adjust-measure
        data:
          subject: thief
          measure: strength
          by: -1
      - type: set-flag
        data:
          flag: thief-fighting
          value: true

  - id: attack
    preposition: with
    indirect: axe
    conditions:
      - type: has-item
        data:
          object: axe
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the axe.
      - type: measure
        data:
          subject: thief
          measure: strength
          max: 1
      - type: chance
        data:
          of: 100
          index: [1..25]
          name: characters-thief-character-axe-1
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your axe misses the thief by an inch.
    triggers:
      - type: response
        data:
          text: The fatal blow catches the thief squarely, and he crumples to the floor.
      - type: adjust-measure
        data:
          subject: thief
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: axe
    conditions:
      - type: has-item
        data:
          object: axe
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the axe.
      - type: chance
        data:
          of: 100
          index: [1..25]
          name: characters-thief-character-axe-2
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your axe misses the thief by an inch.
    triggers:
      - type: response
        data:
          text: A quick thrust pinks the thief's arm, and blood starts to trickle down.
      - type: adjust-measure
        data:
          subject: thief
          measure: strength
          by: -1
      - type: set-flag
        data:
          flag: thief-fighting
          value: true

  - id: attack
    preposition: with
    indirect: rusty-knife
    conditions:
      - type: has-item
        data:
          object: rusty-knife
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the rusty knife.
      - type: measure
        data:
          subject: thief
          measure: strength
          max: 1
      - type: chance
        data:
          of: 100
          index: [1..25]
          name: characters-thief-character-rusty-knife-1
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your rusty knife misses the thief by an inch.
    triggers:
      - type: response
        data:
          text: The fatal blow catches the thief squarely, and he crumples to the floor.
      - type: adjust-measure
        data:
          subject: thief
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: rusty-knife
    conditions:
      - type: has-item
        data:
          object: rusty-knife
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the rusty knife.
      - type: chance
        data:
          of: 100
          index: [1..25]
          name: characters-thief-character-rusty-knife-2
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your rusty knife misses the thief by an inch.
    triggers:
      - type: response
        data:
          text: A quick thrust pinks the thief's arm, and blood starts to trickle down.
      - type: adjust-measure
        data:
          subject: thief
          measure: strength
          by: -1
      - type: set-flag
        data:
          flag: thief-fighting
          value: true

  - id: attack
    triggers:
      - type: response
        data:
          text: >-
            Trying to attack the thief with your bare hands is suicidal - he is armed and you
            are not.

  - id: hello
    triggers:
      - type: response
        data:
          text: The thief bows his head to you in greeting.
