id: troll

synonyms: [nasty troll]
conditions:
  - type: any-of
    data:
      conditions:
        - type: scene
          negate: true
          data: { tag: dark }
        - type: flag
          data: { flag: light }
presence:
  - triggers:
      - type: response
        data:
          text: A nasty-looking troll, brandishing a bloody axe, blocks all passages out of the room.
start: troll-room

holds: [axe]

measures:
  - id: strength
    max: 2
    start: 2
    thresholds:
      - from: 0
        triggers:
          - type: response
            data:
              text: >-
                Almost as soon as the troll breathes his last breath, a cloud of sinister black
                fog envelops him, and when the fog lifts, the carcass has disappeared.
          - type: remove-object
            data:
              object: troll
          - type: move-object
            data:
              object: axe
              to: here
          - type: set-flag
            data:
              flag: troll-flag
              value: true
          - type: achievement
            data: { id: troll-slayer }
      - from: 1

actions:
  - id: attack
    preposition: with
    indirect: sword
    conditions:
      - type: has-item
        data:
          object: sword
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the sword.
      - type: measure
        data:
          subject: troll
          measure: strength
          max: 1
      - type: chance
        data:
          of: 100
          index: [1..60]
          name: characters-troll-character-80
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Clang! Crash! The troll parries.
    triggers:
      - type: response
        data:
          text: 'The fatal blow strikes the troll square in the heart: He dies.'
      - type: adjust-measure
        data:
          subject: troll
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: sword
    conditions:
      - type: has-item
        data:
          object: sword
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the sword.
      - type: chance
        data:
          of: 100
          index: [1..60]
          name: characters-troll-character-109
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your sword misses the troll by an inch.
    triggers:
      - type: response
        data:
          text: The troll is struck on the arm; blood begins to trickle down.
      - type: adjust-measure
        data:
          subject: troll
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: axe
    conditions:
      - type: has-item
        data:
          object: axe
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the axe.
      - type: measure
        data:
          subject: troll
          measure: strength
          max: 1
      - type: chance
        data:
          of: 100
          index: [1..45]
          name: characters-troll-character-axe-1
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your axe misses the troll by an inch.
    triggers:
      - type: response
        data:
          text: 'The fatal blow strikes the troll square in the heart: He dies.'
      - type: adjust-measure
        data:
          subject: troll
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: axe
    conditions:
      - type: has-item
        data:
          object: axe
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the axe.
      - type: chance
        data:
          of: 100
          index: [1..45]
          name: characters-troll-character-axe-2
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your axe misses the troll by an inch.
    triggers:
      - type: response
        data:
          text: The troll is struck on the arm; blood begins to trickle down.
      - type: adjust-measure
        data:
          subject: troll
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: knife
    conditions:
      - type: has-item
        data:
          object: knife
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the knife.
      - type: measure
        data:
          subject: troll
          measure: strength
          max: 1
      - type: chance
        data:
          of: 100
          index: [1..45]
          name: characters-troll-character-knife-1
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your knife misses the troll by an inch.
    triggers:
      - type: response
        data:
          text: 'The fatal blow strikes the troll square in the heart: He dies.'
      - type: adjust-measure
        data:
          subject: troll
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: knife
    conditions:
      - type: has-item
        data:
          object: knife
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the knife.
      - type: chance
        data:
          of: 100
          index: [1..45]
          name: characters-troll-character-knife-2
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your knife misses the troll by an inch.
    triggers:
      - type: response
        data:
          text: The troll is struck on the arm; blood begins to trickle down.
      - type: adjust-measure
        data:
          subject: troll
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: rusty-knife
    conditions:
      - type: has-item
        data:
          object: rusty-knife
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the rusty knife.
      - type: measure
        data:
          subject: troll
          measure: strength
          max: 1
      - type: chance
        data:
          of: 100
          index: [1..45]
          name: characters-troll-character-rusty-knife-1
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your rusty knife misses the troll by an inch.
    triggers:
      - type: response
        data:
          text: 'The fatal blow strikes the troll square in the heart: He dies.'
      - type: adjust-measure
        data:
          subject: troll
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: rusty-knife
    conditions:
      - type: has-item
        data:
          object: rusty-knife
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the rusty knife.
      - type: chance
        data:
          of: 100
          index: [1..45]
          name: characters-troll-character-rusty-knife-2
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your rusty knife misses the troll by an inch.
    triggers:
      - type: response
        data:
          text: The troll is struck on the arm; blood begins to trickle down.
      - type: adjust-measure
        data:
          subject: troll
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: stiletto
    conditions:
      - type: has-item
        data:
          object: stiletto
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the stiletto.
      - type: measure
        data:
          subject: troll
          measure: strength
          max: 1
      - type: chance
        data:
          of: 100
          index: [1..45]
          name: characters-troll-character-stiletto-1
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your stiletto misses the troll by an inch.
    triggers:
      - type: response
        data:
          text: 'The fatal blow strikes the troll square in the heart: He dies.'
      - type: adjust-measure
        data:
          subject: troll
          measure: strength
          by: -1

  - id: attack
    preposition: with
    indirect: stiletto
    conditions:
      - type: has-item
        data:
          object: stiletto
        failure:
          triggers:
            - type: response
              data:
                text: You aren't holding the stiletto.
      - type: chance
        data:
          of: 100
          index: [1..45]
          name: characters-troll-character-stiletto-2
        failure:
          triggers:
            - type: journal
            - type: response
              data:
                text: Your stiletto misses the troll by an inch.
    triggers:
      - type: response
        data:
          text: The troll is struck on the arm; blood begins to trickle down.
      - type: adjust-measure
        data:
          subject: troll
          measure: strength
          by: -1

  - id: attack
    triggers:
      - type: response
        data:
          text: Trying to attack the troll with your bare hands is suicidal.

  - id: give
    indirect: knife
    conditions:
      - type: chance
        data: { name: troll-fed-weapon-knife-give, of: 5, index: 1 }
    triggers:
      - type: response
        data:
          text: >-
            The troll, who is not overly proud, graciously accepts the gift and eats it hungrily. Poor
            troll, he dies from an internal hemorrhage and his carcass disappears in a sinister black
            fog.
      - type: remove-object
        data:
          object: knife
      - type: remove-object
        data:
          object: troll
      - type: move-object
        data:
          object: axe
          to: here
      - type: set-flag
        data:
          flag: troll-flag
          value: true
      - type: achievement
        data: { id: troll-slayer }

  - id: give
    indirect: knife
    triggers:
      - type: response
        data:
          text: >-
            The troll, who is not overly proud, graciously accepts the gift and, being for the moment
            sated, throws it back. Fortunately, the troll has poor control, and the nasty knife falls to
            the floor. He does not look pleased.
      - type: move-object
        data:
          object: knife
          to: here

  - id: give
    indirect: sword
    conditions:
      - type: chance
        data: { name: troll-fed-weapon-sword-give, of: 5, index: 1 }
    triggers:
      - type: response
        data:
          text: >-
            The troll, who is not overly proud, graciously accepts the gift and eats it hungrily. Poor
            troll, he dies from an internal hemorrhage and his carcass disappears in a sinister black
            fog.
      - type: remove-object
        data:
          object: sword
      - type: remove-object
        data:
          object: troll
      - type: move-object
        data:
          object: axe
          to: here
      - type: set-flag
        data:
          flag: troll-flag
          value: true
      - type: achievement
        data: { id: troll-slayer }

  - id: give
    indirect: sword
    triggers:
      - type: response
        data:
          text: >-
            The troll, who is not overly proud, graciously accepts the gift and, being for the moment
            sated, throws it back. Fortunately, the troll has poor control, and the sword falls to the
            floor. He does not look pleased.
      - type: move-object
        data:
          object: sword
          to: here

  - id: give
    triggers:
      - type: response
        data:
          text: >-
            The troll, who is not overly proud, graciously accepts the gift and, not having the most
            discriminating tastes, gleefully eats it.

  - id: throw
    indirect: knife
    conditions:
      - type: chance
        data: { name: troll-fed-weapon-knife-throw, of: 5, index: 1 }
    triggers:
      - type: response
        data:
          text: >-
            The troll, who is remarkably coordinated, catches the nasty knife and eats it hungrily. Poor
            troll, he dies from an internal hemorrhage and his carcass disappears in a sinister black
            fog.
      - type: remove-object
        data:
          object: knife
      - type: remove-object
        data:
          object: troll
      - type: move-object
        data:
          object: axe
          to: here
      - type: set-flag
        data:
          flag: troll-flag
          value: true
      - type: achievement
        data: { id: troll-slayer }

  - id: throw
    indirect: knife
    triggers:
      - type: response
        data:
          text: >-
            The troll, who is remarkably coordinated, catches the nasty knife and, being for the moment
            sated, throws it back. Fortunately, the troll has poor control, and the nasty knife falls to
            the floor. He does not look pleased.
      - type: move-object
        data:
          object: knife
          to: here

  - id: throw
    indirect: sword
    conditions:
      - type: chance
        data: { name: troll-fed-weapon-sword-throw, of: 5, index: 1 }
    triggers:
      - type: response
        data:
          text: >-
            The troll, who is remarkably coordinated, catches the sword and eats it hungrily. Poor troll,
            he dies from an internal hemorrhage and his carcass disappears in a sinister black fog.
      - type: remove-object
        data:
          object: sword
      - type: remove-object
        data:
          object: troll
      - type: move-object
        data:
          object: axe
          to: here
      - type: set-flag
        data:
          flag: troll-flag
          value: true
      - type: achievement
        data: { id: troll-slayer }

  - id: throw
    indirect: sword
    triggers:
      - type: response
        data:
          text: >-
            The troll, who is remarkably coordinated, catches the sword and, being for the moment sated,
            throws it back. Fortunately, the troll has poor control, and the sword falls to the floor. He
            does not look pleased.
      - type: move-object
        data:
          object: sword
          to: here

  - id: throw
    triggers:
      - type: response
        data:
          text: >-
            The troll, who is remarkably coordinated, catches the gift and, not having the most
            discriminating tastes, gleefully eats it.

  - id: get
    triggers:
      - type: response
        data:
          text: >-
            The troll spits in your face, grunting "Better luck next time" in a rather barbarous accent.

  - id: break
    triggers:
      - type: response
        data:
          text: The troll laughs at your puny gesture.

  - id: listen
    triggers:
      - type: response
        data:
          text: >-
            Every so often the troll says something, probably uncomplimentary, in his guttural tongue.

  - id: tell
    triggers:
      - type: response
        data:
          text: The troll isn't much of a conversationalist.

  - id: look
    triggers:
      - type: response
        data:
          text: >-
            A nasty-looking troll, brandishing a bloody axe, blocks all passages out of the room.

  - id: hello
    triggers:
      - type: response
        data:
          text: The troll bows his head to you in greeting.
