id: attic
tags: [dark]

meta:
  title: Attic

presence:
  - requires:
      - type: flag
        data:
          flag: light
    triggers:
      - type: response
        data:
          text: This is the attic. The only exit is a stairway leading down.
  - triggers:
      - type: response
        data:
          text: It is pitch black. You are likely to be eaten by a grue.

objects: [attic-table, knife, rope]

navigation:
  - id: down
    triggers:
      - type: change-scene
        data:
          scene: kitchen
